---
grails:
    profile: web
    codegen:
        defaultPackage: timesheet
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

server:
    port: 9001

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

endpoints:
    jmx:
        unique-names: true

environments:
    development:
#        dataSource:
#            dbCreate: create-drop
#            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        dataSource:
             pooled: true
             dbCreate: update
             jmxExport: true
             url: jdbc:mysql://10.0.0.3:3306/cargahoras_dev
             driverClassName: com.mysql.jdbc.Driver
             dialect: org.hibernate.dialect.MySQL5InnoDBDialect
             username: admin
             password: maipu$671
             properties:
                  jmxEnabled: true
                  initialSize: 5
                  maxActive: 50
                  minIdle: 5
                  maxIdle: 25
                  maxWait: 10000
                  maxAge: 600000
                  timeBetweenEvictionRunsMillis: 5000
                  minEvictableIdleTimeMillis: 60000
                  validationQuery: SELECT 1
                  validationQueryTimeout: 3
                  validationInterval: 15000
                  testOnBorrow: true
                  testWhileIdle: true
                  testOnReturn: false
                  jdbcInterceptors: ConnectionState;StatementCache(max=200)
                  defaultTransactionIsolation: 2
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/cargahoras_test
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: admin
            password: maipu$671
            properties:
                  jmxEnabled: true
                  initialSize: 5
                  maxActive: 50
                  minIdle: 5
                  maxIdle: 25
                  maxWait: 10000
                  maxAge: 600000
                  timeBetweenEvictionRunsMillis: 5000
                  minEvictableIdleTimeMillis: 60000
                  validationQuery: SELECT 1
                  validationQueryTimeout: 3
                  validationInterval: 15000
                  testOnBorrow: true
                  testWhileIdle: true
                  testOnReturn: false
                  jdbcInterceptors: ConnectionState;StatementCache(max=200)
                  defaultTransactionIsolation: 2
    production:
        dataSource:
            pooled: true
            dbCreate: update
            jmxExport: true
            url: jdbc:mysql://10.0.0.3:3306/cargahoras_prod
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: admin
            password: maipu$671
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState;StatementCache(max=200)
                defaultTransactionIsolation: 2
